### ISSUE TITLE
What is the reason for the generated CSS classes?

### ISSUE THREAD

**Issue by mystrdat** [mderrick/react-html5video#84]
That is absolutely not useful, why is this a part of the library?

**Comment by mderrick** [comment]
You're not supposed to modify the CSS of the component. You should make your own components and use the HoC to access video properties if you want a custom styled video player. This is a normal approach to encapsulating CSS so it does not conflict with other global CSS by the integrating individual. The DefaultPlayer is more of a working example of the HoC than it is the main purpose of this repository.

**Comment by mystrdat** [comment]
Encapsulating CSS should not be the purpose of this library, rather the stack above it. You have only purposefully disabled common ways to modify the default skin, forcing any custom usage to define their own HOC, which cripples the most basic usecases because for the most part only minor modifications are necessary. I would suggest you reconsider bringing fresh opinionated principles into libraries, especially when there is almost no real gain from it.

**Comment by mderrick** [comment]
Encapsulating your own CSS is very much integral to any library. The hashed classes are there to ensure my component works all the time, every time. This is a huge gain and a great practice.

I will not officially support overriding CSS using global selectors because this locks me into a specific DOM and class name convention. I don't want to release minor versions if I wish to change a `div` to a `span` because I support users who want to override the components with their own global CSS.

If I un-hash them so they do not change per build then they may change less often but they will still be subject to change without notice. The hashing just highlights this issue as it happens more regularly.

I will consider un-hashing them but instead name spacing in a BEM-ish fashion but the fact that they might still change falls squarely on the users shoulders for using it in an unsupported fashion.

In fact I'd probably lock the version in your `package.json` down to the minor version to ensure you don't get any breaking changes. However if you do this you might as well do this now and style using the hashed classes.

**Comment by mystrdat** [comment]
Global selectors aren't and were never as much of a problem as they are made to be today, in fact the convenience they bring is very valuable. You seem opinionated on how things should work, which I would have no problem with as long as it doesn't limit my usecases. Since writing a custom HOC here equals implementing 90% of the player logic myself, it simply ceases to be useful, when, as example, all I wanted was to change the play button color to red. I do understand your reasoning, although I do not believe it should be solved on the level of individual libraries. In the meantime, I will rollback to videojs as it is simply requires less work to use. Thanks for explaining your position.

**Comment by mderrick** [comment]
You are right, this does mean you have to do 90% of the leg work to only customise a small piece of the player and I'm also not a fan of this. The only problem is that my ultimate goal was to just have a nice way to get access to video props to create a bunch of completely new skins. The DefaultPlayer just being an example of one.

I think I will certainly un-hash the classnames for those who do want to go down this route and give you ultimate control (but name spacing them still to avoid clashes, something like `rh5v-name_local`). I just want to be careful when saying that I officially support this way of customising because as soon as I do I have to be really careful about changing the DOM every time I make a change. It makes for painful maintenance when I have to consider that someone, somewhere has done something like `.play-button > div { color: red; }`.

Also VideoJS does much much more than this does. I don't think I ever intended to compete with what that does. I just thought the HoC could create a great eco system of cool third party skins.

**Comment by mderrick** [comment]
https://github.com/mderrick/react-html5video/commit/ccae6effc84195c8a70b9a3d83c78f8c0a305c76

**Comment by mderrick** [comment]
Released in 2.1.0. It would be great to know if that change would have assisted you in anyway, even if you are going back to using VideoJS. Thanks.

**Comment by mystrdat** [comment]
That was fast and certainly solves the easy skinning problem, thank you!

> It makes for painful maintenance when I have to consider that someone, somewhere has done something like

If the opinion matters to you, I believe this shouldn't be a worry of yours. Updates for the sake of updates should be subject to breaking changes and maintainers should be aware of it. In this case it's somewhat of a milder problem, since the breaking changes would be visually recognizable and probably very easily fixed with minor adjustments to selectors or rules. IMHO that is the price of convenience and all libraries working with the HTML DOM are subject to it in one way or another. After all there can be a guy with `div { display: inline }` in his app and break the whole thing anyway, we're still in the wild web as long as we don't transition to Web Components.
